### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by thomasgouveia**
@sameo , If you can delete other PRs :) This is the good one !

### CODE REVIEW

**Comment by sameo** [comment]
> @sameo , If you can delete other PRs :) This is the good one !

Thanks @thomasgouveia. I'd love to merge it, but it needs to be rebased...

**Comment by thomasgouveia** [comment]
@sameo, I did the command `git pull --rebase origin main` but it seems that everything is up to date on my side ? 

image

**Comment by sameo** [comment]
It still won't apply, fwiw.

**Comment by sameo** [comment]
Encore des erreurs de build a fixer, @thomasgouveia

**Pull request merged**
